# Generated by Django 4.2.5 on 2023-10-07 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='properties',
        ),
        migrations.AddField(
            model_name='properties',
            name='properties',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties_product', to='store.product'),
        ),
    ]
