# Generated by Django 4.2.5 on 2023-10-07 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_properties_properties_properties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties',
            old_name='properties',
            new_name='product',
        ),
    ]
