# Generated by Django 4.2.5 on 2023-10-07 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_properties_properties_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties_product', to='store.product'),
        ),
    ]
